# Generated by Django 4.2.2 on 2023-07-12 06:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_accounts_avatar_alter_accounts_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Accounts3',
        ),
    ]
