# Generated by Django 4.2.2 on 2023-07-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanLuis', '0005_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidad',
            name='imagen',
            field=models.ImageField(upload_to='media'),
        ),
    ]
