# Generated by Django 4.2.2 on 2023-07-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanLuis', '0006_alter_modalidad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidad',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modalidad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='modalidades'),
        ),
        migrations.AlterField(
            model_name='modalidad',
            name='subtitulo',
            field=models.CharField(max_length=100),
        ),
    ]
